### ISSUE TITLE
Login screen doesn't show "Invalid login" message

### ISSUE THREAD

**Issue by andytor** [thedannywahl/moodle-theme_elegance#97]
If a user enters invalid credentials on the custom login screen then the form will refresh (with entered values cleared) but without showing the invalid login message.  If the use of the theme's login page is disabled this then works correctly.

**Comment by thedannywahl** [comment]
this is a result of [MDL-40160](https://tracker.moodle.org/browse/MDL-40160)- the login page hasn't been converted to a renderer - so as they add/change login methods I can't track it in the theme.  Basically only 2.6 methods will work
